### ISSUE TITLE
Issues with "Edge Detection" and other Image Processing examples

### ISSUE THREAD

**Issue by greg-kennedy** [processing/processing-examples#11]
The "Examples -> Topics -> Image Processing" section is a bit confusing right now.

Basically, there are three examples that use a "convolution" filter with a 3x3 kernel:
* Blur - this one seems fine
* Edge Detection - this one seems to be a "sharpen" filter, incorrectly named
* Convolution - this one is the same as "sharpen", but interactive.

Missing from here is a true "edge detection" filter (Sobel, Laplacian, etc), and there is a fair amount of duplication in here with methods etc.

I'd be happy to take a stab at sorting these out as follows:
* Blur -> no changes
* Edge Detection -> rename to "Sharpen"
* (new) Edge Detection -> add Laplacian (based on changes in my branch here: https://github.com/greg-kennedy/processing-examples/commit/0c97a9fcca228d3482571e095bcf42615aa9c6e0)
* Convolution -> Add mouse click to switch kernels at run-time, and put a few different ones to try out

and standardize comments / methods / etc. between them all.  Sound good?

**Comment by greg-kennedy** [comment]
This can be closed, unless there are changes in https://github.com/processing/processing-website that need to be made.

**Comment by SableRaf** [comment]
Good heads up @greg-kennedy. Closing. Thanks again for your contributions!

Note: The edge detection, sharpen, and convolution examples are not currently included on the website. They might be good first contributions for someone. Feel free to create an issue over there if you have a moment. Otherwise I'll add it to my list :)
