### ISSUE TITLE
Blur backgound behind a custom shape

### ISSUE THREAD

**Issue by pmoliveira2000** [processing/processing-examples#15]
Hello.
I'd like to know if there is a way to blur the backgound behind a moving custom shape built with beginDraw(), vertex(), endDraw().
The backgound could be other shapes and lines, etc., instead of a loaded picture.
Thank you.
Best regards,
Pedro @ PORTUGAL

**Comment by SableRaf** [comment]
Hi Pedro,
This repository is for reporting issues in the Processing examples. 
For questions about your own projects, please use [the Processing forum](https://discourse.processing.org/). Thanks! 😊
