### ISSUE TITLE
Displaying Unnecessary  `<br/> ` Tags in CharactersStrings example Description

### ISSUE THREAD

**Issue by Rahulhanje** [processing/processing-examples#23]
Displaying Unnecessary `<br/> ` Tags in CharactersStrings example Description which are also visible same in website also as mentioned below image please make correction on those typos 
![image](https://github.com/user-attachments/assets/1f40fa10-ccb9-4672-b552-6b03d3a08371)

**Comment by SableRaf** [comment]
Thanks raising this issue @Rahulhanje! The fixes were implemented here and rolled to the website in https://github.com/processing/processing-website/commit/6e2276ca96bd7254c233c3901280869b8cecebc3
