### ISSUE TITLE
TWO_PI example contains erroneous character instead of real semicolon

### ISSUE THREAD

**Issue by joshi1983** [processing/processing-examples#25]
### Example Location

https://processing.org/reference/TWO_PI.html

### Type of Issue

Syntax Error(s)

### Describe the Issue

The size(400,400)；line ends with a character that looks like a semicolon but it is not actually a semicolon.  The difference causes errors if you paste the example into Processing.

### Suggested Fix

I suggest replacing the erroneous character with an actual semicolon.  I made a pull request to do that and only that here:
https://github.com/processing/processing-website/pull/561

**Comment by SableRaf** [comment]
Well spotted! Thanks so much for catching that 😃

**Comment by SableRaf** [comment]
Hey @joshi1983! I just realized that the PR you made (https://github.com/processing/processing-website/pull/561) was to the wrong repository—my bad for not catching this sooner. The examples should actually be edited in https://github.com/processing/processing-examples.

For more details on updating examples, please check out this documentation:

https://github.com/processing/processing-website/blob/main/docs/examples.md#which-files-should-edit

Thanks so much for your work, and sorry again for the mix-up! Please make the same PR to the processing-examples repo and I'll merge it.

**Comment by joshi1983** [comment]
Sorry for overlooking the documentation about the processing-examples repository and how files there are processed and copied to processing-website repository.  I see the TWO_PI example has the correct semicolon at https://processing.org/reference/TWO_PI.html, though.

After reading the documentation I'm still a little confused, though.  I see content/examples/Basic and content/examples/Topics directories from processing-website are basically copies from processing-examples repository but content/references/examples/processing/TWO_PI is not from any of those.  I don't see TWO_PI in the processing-examples repository.  Can you share a link to the processing-examples repository file that gets copied or converted into content/references/examples/processing/TWO_PI/TWO_PI.pde?

**Comment by SableRaf** [comment]
Hey @joshi1983,

I want to apologize for the confusion earlier. You were correct with your PR. The mix-up on my end came from overlooking that we were specifically dealing with an [example in the reference section](https://github.com/processing/processing-website/blob/main/docs/reference.md#examples) and not general Processing examples. Thanks again for catching this!

There’s no further action needed, the issue was fixed on the website with your existing PR. I appreciate your patience and attention to detail.

Thanks again!
