### ISSUE TITLE
Multiple Particle Systems and Flocking Examples not running

### ISSUE THREAD

**Issue by mmmmrrccss** [processing/processing-examples#4]
I am trying to run the Multiple Particle Systems and Flocking Examples but they're not running on my device. They throw up the following errors: 

_Cannot find a class or type named “ParticleSystem”
Cannot find a class or type named “Flock”_

I'm very keen to work with these so please can you advise as to why they arent running/ how to link with the correct class or types?

https://processing.org/examples/flocking.html
https://processing.org/examples/multipleparticlesystems.html

**Comment by SableRaf** [comment]
Hello @mmmmrrccss and thanks for your question. 

If you look closely, you will notice that the examples in question have multiple tabs. You need to have all these as .pde files in your project. The easier way to do this is open these examples directly in the Processing IDE. Go to `File > Examples...` menu and navigate to the example you want to use.

For further questions, I recommend asking on the Processing Foundation forum: https://discourse.processing.org/
