### ISSUE TITLE
Undesired behaviour of examples "Handles" and "Scrollbar"

### ISSUE THREAD

**Issue by trikaphundo** [processing/processing-examples#8]
Hello. There are two example programs, Handles and Scrollbar, that behave unexpectedly. Both are in the [GUI topic](https://github.com/processing/processing-examples/tree/main/Topics/GUI). This strange behaviour is also present in their interactive [example webpages](https://processing.org/examples/handles.html).

The undesired/unexpected behaviour is that the a handle—or scrollbar—can be activated by hovering the mouse over it while having a mouse button pressed. This is undesired and unexpected, as handles and scrollbars are common GUI elements which are supposed to activate only when you click on them, after the mouse pointer is over them, not before.

To see exactly the problem do the following:
1. Run either of the sketches.
2. Hold a mouse button pressed.
3. Move the mouse pointer to a handle (or scrollbar).

**Comment by SableRaf** [comment]
Thanks @trikaphundo! 👍
